baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rez"

theme = "docsy"

navbar_logo = true

staticDir = ["static"]


disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"
